### ISSUE TITLE
<style>中css失效

### ISSUE THREAD

**Issue by jaysding** [andurils/vue-code-view#11]
当在<style>块中编写css时，如果不在css值的后面加分号";", <style>块内的css就都会失效！

**Comment by jaysding** [comment]
在style lang=scss中写样式时，这种符号选择器的组合”&>*“，如果一旦中间多出空格(& > * )，也会使css失效。

**Comment by andurils** [comment]
目前该组件不支持 CSS 格式的校验和格式化功能。因此，在使用时请尽量保持您的 CSS 代码格式的标准化。

**Comment by jaysding** [comment]
> 
好的，希望作者可以增加css不支持格式标准化的提示，以避免开发者在使用过程中浪费不必要的排查时间


> 目前该组件不支持 CSS 格式的校验和格式化功能。因此，在使用时请尽量保持您的 CSS 代码格式的标准化。
