### ISSUE TITLE
vue-code-view 样式极易影响示例

### ISSUE THREAD

**Issue by trcat** [andurils/vue-code-view#21]
部分样式因为不是作用在类名上，会对示例进行影响，从而产生副作用，对校验产生不必要的影响。

如下图所示，此处样式被 vue-code-view 自身样式影响，这是我们不期望的

![image](https://user-images.githubusercontent.com/23648263/208599419-95b63781-0ffb-4e85-94c7-c976d703d0a6.png)

**Comment by andurils** [comment]
closed by pr #28
