### ISSUE TITLE
下载的版本里面 没有css样式文件

### ISSUE THREAD

**Issue by daly-dai** [andurils/vue-code-view#6]
![image](https://user-images.githubusercontent.com/23162608/150918447-6a5795bd-2363-4424-b570-02741f9c22b1.png)
文档可能没有及时更新

**Comment by andurils** [comment]
新版本打包构建时，CSS放在一起了没有独立出来，已经在readme中说明了
[readme#示例](https://github.com/andurils/vue-code-view/blob/main/README.zh-CN.md#-%E7%A4%BA%E4%BE%8B)
blog中内容暂未更新

**Comment by andurils** [comment]
blog中内容已更新 #7
